{"name": "Тест Ошибка при авторизации с неверным паролем", "status": "passed", "start": 1738680652378, "stop": 1738680652826, "uuid": "e73fc17a-5b0c-4878-8132-f3a3983de731", "historyId": "1c544dc5b0af767679c663bda106b45b", "testCaseId": "1c544dc5b0af767679c663bda106b45b", "fullName": "tests.test_login_courier.TestLoginCourier#test_auth_with_non_existent_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "pyreva.local"}, {"name": "thread", "value": "41853-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}