{"name": "Тест Ошибка при авторизации с неверным паролем", "status": "passed", "start": 1738680780463, "stop": 1738680781026, "uuid": "24cf465c-f027-4abd-b482-97f300751637", "historyId": "1c544dc5b0af767679c663bda106b45b", "testCaseId": "1c544dc5b0af767679c663bda106b45b", "fullName": "tests.test_login_courier.TestLoginCourier#test_auth_with_non_existent_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "pyreva.local"}, {"name": "thread", "value": "41910-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}